POST localhost:8080/user/adm/create_by_admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ2YWxpIiwiaWF0IjoxNjgxODQ4MTYzLCJleHAiOjE2ODE4NDk5NjN9.GnENoCDa7RQqXuf7xPxvgIgG6wsgDz2lyaU3hmiBdpM

{
  "name": "Saloh",
  "username": "saloh",
  "password": "123"
}

###

PUT localhost:8080/user/public/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ2YWxpIiwiaWF0IjoxNjgxODQ2NTQ5LCJleHAiOjE2ODE4NDgzNDl9.zd-iFxiZw8iRVe76tuZhy_T0DhzEzefeLde1aXbA2w4

{
  "name": "jon",
  "username": "joni",
  "password": "12"
}

###

DELETE localhost:8080/user/public/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ2YWxpIiwiaWF0IjoxNjgxODQ3ODU3LCJleHAiOjE2ODE4NDk2NTd9.viKN4zEZlCJMUfV2vgCmgbLFBavB_nDW9I1XKgD7iBo

###

GET localhost:8080/user/adm/get_all
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ2YWxpIiwiaWF0IjoxNjgxODQ4MTYzLCJleHAiOjE2ODE4NDk5NjN9.GnENoCDa7RQqXuf7xPxvgIgG6wsgDz2lyaU3hmiBdpM

###

GET localhost:8080/user/adm/get/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ2YWxpIiwiaWF0IjoxNjgxODQ4MTYzLCJleHAiOjE2ODE4NDk5NjN9.GnENoCDa7RQqXuf7xPxvgIgG6wsgDz2lyaU3hmiBdpM

